language: rust
allow_failures:
  - rust: nightly
rust:
  - 1.36.0
  - beta
  - nightly
  - stable
script:
  - pushd ./scripts
  - ./test-stable.sh
  - ([ $TRAVIS_RUST_VERSION != nightly ] || ./test-nightly.sh)
  - popd
