[package]
authors = ["Simon Sapin <simon.sapin@exyr.org>"]
categories = ["data-structures"]
description = "'Small vector' optimization: store up to a small number of items on the stack"
documentation = "https://doc.servo.org/smallvec/"
edition = "2018"
keywords = ["small", "vec", "vector", "stack", "no_std"]
license = "MIT/Apache-2.0"
name = "smallvec"
readme = "README.md"
repository = "https://github.com/servo/rust-smallvec"
version = "0.6.10"

[package.metadata.docs.rs]
features = ["may_dangle", "specialization", "std", "union"]

[dependencies]
serde = { version = "1", optional = true }

[dev_dependencies]
bincode = "1.0.1"

[features]
const_generics = []
may_dangle = []
specialization = []
std = []
union = []
